// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: indicator_ha

#include "../ui.h"

void ui_screen_ha_mix_screen_init(void)
{
ui_screen_ha_mix = lv_obj_create(NULL);
lv_obj_clear_flag( ui_screen_ha_mix, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_switch1 = lv_btn_create(ui_screen_ha_mix);
lv_obj_set_width( ui_switch1, 214);
lv_obj_set_height( ui_switch1, 164);
lv_obj_set_x( ui_switch1, 22 );
lv_obj_set_y( ui_switch1, 268 );
lv_obj_add_flag( ui_switch1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_switch1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_switch1, lv_color_hex(0x292829), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_switch1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_switch1, 20, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_switch1, lv_color_hex(0x292829), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_switch1, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_shadow_color(ui_switch1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_shadow_opa(ui_switch1, 0, LV_PART_MAIN| LV_STATE_CHECKED);

ui_switch1_logo1 = lv_img_create(ui_switch1);
lv_img_set_src(ui_switch1_logo1, &ui_img_ic_switch2_off_png);
lv_obj_set_width( ui_switch1_logo1, LV_SIZE_CONTENT);  /// 45
lv_obj_set_height( ui_switch1_logo1, LV_SIZE_CONTENT);   /// 45
lv_obj_set_x( ui_switch1_logo1, 39 );
lv_obj_set_y( ui_switch1_logo1, 10 );
lv_obj_add_flag( ui_switch1_logo1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_switch1_logo1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_switch1_label1 = lv_label_create(ui_switch1);
lv_obj_set_width( ui_switch1_label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_switch1_label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_switch1_label1, 0 );
lv_obj_set_y( ui_switch1_label1, -5 );
lv_obj_set_align( ui_switch1_label1, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_switch1_label1,"Switch1");
lv_obj_set_style_text_color(ui_switch1_label1, lv_color_hex(0x9E9E9E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_switch1_label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_switch1_label1, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_switch2 = lv_btn_create(ui_screen_ha_mix);
lv_obj_set_width( ui_switch2, 214);
lv_obj_set_height( ui_switch2, 78);
lv_obj_set_x( ui_switch2, 244 );
lv_obj_set_y( ui_switch2, 268 );
lv_obj_add_flag( ui_switch2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CHECKABLE );   /// Flags
lv_obj_clear_flag( ui_switch2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM );    /// Flags
lv_obj_set_style_radius(ui_switch2, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_switch2, lv_color_hex(0x282828), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_switch2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_switch2, lv_color_hex(0x292829), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_switch2, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_switch2_logo1 = lv_img_create(ui_switch2);
lv_img_set_src(ui_switch2_logo1, &ui_img_ic_switch1_off_png);
lv_obj_set_x( ui_switch2_logo1, 120 );
lv_obj_set_y( ui_switch2_logo1, 2 );
lv_obj_add_flag( ui_switch2_logo1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_switch2_logo1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_switch2_label1 = lv_label_create(ui_switch2);
lv_obj_set_width( ui_switch2_label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_switch2_label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_switch2_label1, 16 );
lv_obj_set_y( ui_switch2_label1, 22 );
lv_label_set_text(ui_switch2_label1,"Switch2");
lv_obj_set_style_text_color(ui_switch2_label1, lv_color_hex(0x9E9E9E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_switch2_label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_switch2_label1, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_switch_btn3 = lv_btn_create(ui_screen_ha_mix);
lv_obj_set_width( ui_switch_btn3, 214);
lv_obj_set_height( ui_switch_btn3, 78);
lv_obj_set_x( ui_switch_btn3, 243 );
lv_obj_set_y( ui_switch_btn3, 351 );
lv_obj_add_flag( ui_switch_btn3, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_switch_btn3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_switch_btn3, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_switch_btn3, lv_color_hex(0x282828), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_switch_btn3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_switch_btn3, lv_color_hex(0x292829), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_switch_btn3, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_switch3_label1 = lv_label_create(ui_switch_btn3);
lv_obj_set_width( ui_switch3_label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_switch3_label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_switch3_label1, 16 );
lv_obj_set_y( ui_switch3_label1, 22 );
lv_label_set_text(ui_switch3_label1,"Switch3");
lv_obj_set_style_text_color(ui_switch3_label1, lv_color_hex(0x9E9E9E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_switch3_label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_switch3_label1, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_switch3 = lv_switch_create(ui_switch_btn3);
lv_obj_set_width( ui_switch3, 80);
lv_obj_set_height( ui_switch3, 30);
lv_obj_set_x( ui_switch3, 115 );
lv_obj_set_y( ui_switch3, 20 );
lv_obj_add_state( ui_switch3, LV_STATE_CHECKED );     /// States

lv_obj_set_style_radius(ui_switch3, 40, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_switch3, lv_color_hex(0x4F4F4F), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_switch3, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_switch3, LV_GRAD_DIR_NONE, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_switch3, lv_color_hex(0x529D53), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_switch3, 255, LV_PART_INDICATOR| LV_STATE_CHECKED);

lv_obj_set_style_bg_color(ui_switch3, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_switch3, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_panel_top_2 = lv_obj_create(ui_screen_ha_mix);
lv_obj_set_width( ui_panel_top_2, 480);
lv_obj_set_height( ui_panel_top_2, 30);
lv_obj_set_x( ui_panel_top_2, 0 );
lv_obj_set_y( ui_panel_top_2, 10 );
lv_obj_set_align( ui_panel_top_2, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_panel_top_2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_panel_top_2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_panel_top_2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_panel_top_2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_panel_top_2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_time_ha_data1 = lv_label_create(ui_panel_top_2);
lv_obj_set_width( ui_time_ha_data1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_time_ha_data1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_time_ha_data1, 15 );
lv_obj_set_y( ui_time_ha_data1, 0 );
lv_obj_set_align( ui_time_ha_data1, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_time_ha_data1,"21:20");
lv_obj_set_style_text_font(ui_time_ha_data1, &ui_font_font0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_screen_home_data_label2 = lv_label_create(ui_panel_top_2);
lv_obj_set_width( ui_screen_home_data_label2, 316);
lv_obj_set_height( ui_screen_home_data_label2, 21);
lv_obj_set_x( ui_screen_home_data_label2, 0 );
lv_obj_set_y( ui_screen_home_data_label2, 15 );
lv_obj_set_align( ui_screen_home_data_label2, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_screen_home_data_label2,"Home Assistant\n");
lv_obj_set_style_text_color(ui_screen_home_data_label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_screen_home_data_label2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_screen_home_data_label2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_screen_home_data_label2, &ui_font_font0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wifi__st_button_ha_data1 = lv_btn_create(ui_panel_top_2);
lv_obj_set_width( ui_wifi__st_button_ha_data1, 60);
lv_obj_set_height( ui_wifi__st_button_ha_data1, 60);
lv_obj_set_align( ui_wifi__st_button_ha_data1, LV_ALIGN_RIGHT_MID );
lv_obj_add_flag( ui_wifi__st_button_ha_data1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_wifi__st_button_ha_data1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_wifi__st_button_ha_data1, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_wifi__st_button_ha_data1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_wifi__st_button_ha_data1, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT );

ui_wifi_st_1 = lv_img_create(ui_wifi__st_button_ha_data1);
lv_img_set_src(ui_wifi_st_1, &ui_img_wifi_disconet_png);
lv_obj_set_width( ui_wifi_st_1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wifi_st_1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_wifi_st_1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_wifi_st_1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_wifi_st_1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_add_event_cb(ui_switch1, ui_event_switch1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_switch2, ui_event_switch2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_switch3, ui_event_switch3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_wifi__st_button_ha_data1, ui_event_wifi__st_button_ha_data1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_screen_ha_mix, ui_event_screen_ha_mix, LV_EVENT_ALL, NULL);

}
