// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: indicator_ha

#include "ui.h"

void switch_event_cb(lv_event_t * e)
{
	// Your code here
}

void switch_arc_event_cb(lv_event_t * e)
{
	// Your code here
}

void ui_event_wifi_config(lv_event_t * e)
{
	// Your code here
}

void ui_event_wifi_start(lv_event_t * e)
{
	// Your code here
}

void mqtt_addr_changed(lv_event_t * e)
{
	// Your code here
}
